% AUTHOR - DEVESH BHIMSARIA
% Program to score sequences from MinSeqs stored in a resf.mat file generated by run_minseqfind_1.m

% Sequences of length longer than 1000 will be ignored. As that takes much longer time for scoring

seq_file='sequences_to_score.txt'; % FILE CONTAINING SEQUENCES
load_resf='MinSeqFindFunct-op/S07_166_S07_998/resf.mat'; % PATH FOR THE MinSeq RESF.MAT
op_file='MinSeqScoring_output.txt';% NAME OF THE OUTPUT FILE

path_files='MinSeqFindFunct';
addpath(path_files);
load (load_resf);

chip_scoring_version=1;
max_cut_i=1;
seqsx_inx_c=seqsx_inx_c_arr{max_cut_i};
seqx=get_inx_seqs_gp_v1(seqsx_inx_c,l,max_half_nmer);
seeds_to_contx=min(seeds_to_cont,length(seqsx_inx_c));
all_len_c=zeros(seeds_to_contx,1);
all_len_nox_c=zeros(seeds_to_contx,1);
for ix=1:seeds_to_contx
    all_len_c(ix)=find(seqx{ix}~='N',1,'last');
    all_len_nox_c(ix)=length(find(seqx{ix}~='N'));
end
if chip_scoring_version==1
int_chip_seq_arrx=...
    chip_seq_count_v2(max_gap,min_half_nmer,max_half_nmer,seqsx_inx_c_arr{max_cut_i},l,...
    pow_factor,all_len_nox_c,int_nu2x_c_arr2{max_cut_i},seq_file,min_nmer,max_nmer);
else
int_chip_seq_arrx=...
    chip_seq_count_v1(max_gap,min_half_nmer,max_half_nmer,seqsx_inx_c_arr{max_cut_i},l,...
    pow_factor,all_len_nox_c,int_nu2x_c_arr2{max_cut_i},seq_file,min_nmer,max_nmer);
end
dlmwrite(op_file,int_chip_seq_arrx{1});
